// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ActivityRoomInfo.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(YF_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define YF_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if YF_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/YFProtocolBuffers.h>
#else
 #import <YFUtils/YFUtils.h>
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ActivityRoomInfoRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (YFExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c YFExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
YF_FINAL @interface ActivityRoomInfoRoot : YFRootObject
@end

#pragma mark - ActivityRoomInfo

typedef YF_ENUM(ActivityRoomInfo_FieldNumber) {
  ActivityRoomInfo_FieldNumber_UserId = 1,
  ActivityRoomInfo_FieldNumber_ExtendsInfo = 2,
};

/**
 * 活动房间数据
 **/
YF_FINAL @interface ActivityRoomInfo : YFMessage

/** 用户ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 用户扩展信息，包括用户的name，icon等 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *extendsInfo;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
