// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FetchActivityResp.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(YF_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define YF_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if YF_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/YFProtocolBuffers.h>
#else
 #import <YFUtils/YFUtils.h>
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - FetchActivityRespRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (YFExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c YFExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
YF_FINAL @interface FetchActivityRespRoot : YFRootObject
@end

#pragma mark - FetchActivityResp

typedef YF_ENUM(FetchActivityResp_FieldNumber) {
  FetchActivityResp_FieldNumber_RoomNums = 1,
  FetchActivityResp_FieldNumber_RoomWeight = 2,
};

/**
 * 返回当前活动
 **/
YF_FINAL @interface FetchActivityResp : YFMessage

/** 房间人数 */
@property(nonatomic, readwrite) uint32_t roomNums;

/** 房间权重 */
@property(nonatomic, readwrite) uint32_t roomWeight;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
