// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(YF_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define YF_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if YF_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/YFProtocolBuffers.h>
#else
 #import <YFUtils/YFUtils.h>
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class ActivityRoomInfo;
@class HistoryRankingInfo;
@class HistoryRankingInfoV2;
@class RankInfo;
@class UserRankInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MessageRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (YFExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c YFExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
YF_FINAL @interface MessageRoot : YFRootObject
@end

#pragma mark - RankingRemoveReq

typedef YF_ENUM(RankingRemoveReq_FieldNumber) {
  RankingRemoveReq_FieldNumber_BundleId = 1,
  RankingRemoveReq_FieldNumber_RankingId = 2,
  RankingRemoveReq_FieldNumber_UserId = 3,
  RankingRemoveReq_FieldNumber_UserGeo = 4,
};

/**
 * 移除排行榜中黑名单的用户 /v1/r/remove
 **/
YF_FINAL @interface RankingRemoveReq : YFMessage

/** 应用标识ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *bundleId;

/** 排行榜ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *rankingId;

/** 用户ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 用户地区编码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userGeo;

@end

#pragma mark - RankingScoreCommitReq

typedef YF_ENUM(RankingScoreCommitReq_FieldNumber) {
  RankingScoreCommitReq_FieldNumber_BundleId = 1,
  RankingScoreCommitReq_FieldNumber_RankingId = 2,
  RankingScoreCommitReq_FieldNumber_UserId = 3,
  RankingScoreCommitReq_FieldNumber_UserGeo = 4,
  RankingScoreCommitReq_FieldNumber_ScoreArray = 5,
  RankingScoreCommitReq_FieldNumber_ExtendsInfo = 6,
};

/**
 * 用户成绩提交 /v1/r/commit
 **/
YF_FINAL @interface RankingScoreCommitReq : YFMessage

/** 应用标识ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *bundleId;

/** 排行榜ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *rankingId;

/** 用户ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 需不需要榜单ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userGeo;

/** 全球榜成绩（3个指标） */
@property(nonatomic, readwrite, strong, null_resettable) YFUInt32Array *scoreArray;
/** The number of items in @c scoreArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger scoreArray_Count;

/** 用户扩展信息，包括用户的name，icon */
@property(nonatomic, readwrite, copy, null_resettable) NSString *extendsInfo;

@end

#pragma mark - FetchRankingReq

typedef YF_ENUM(FetchRankingReq_FieldNumber) {
  FetchRankingReq_FieldNumber_BundleId = 1,
  FetchRankingReq_FieldNumber_RankingId = 2,
  FetchRankingReq_FieldNumber_UserGeo = 3,
  FetchRankingReq_FieldNumber_Start = 4,
  FetchRankingReq_FieldNumber_End = 5,
};

/**
 * 获取榜单请求 /v1/r/fetch
 **/
YF_FINAL @interface FetchRankingReq : YFMessage

/** 应用标识ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *bundleId;

/** 榜单ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *rankingId;

/** 用户geo */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userGeo;

/** 开始位置，名次 */
@property(nonatomic, readwrite) uint32_t start;

/** 结束位置，名次 */
@property(nonatomic, readwrite) uint32_t end;

@end

#pragma mark - FetchRankingResp

typedef YF_ENUM(FetchRankingResp_FieldNumber) {
  FetchRankingResp_FieldNumber_UserInfosArray = 1,
};

/**
 * 获取榜单响应
 **/
YF_FINAL @interface FetchRankingResp : YFMessage

/** 排榜信息，列表形式 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<RankInfo*> *userInfosArray;
/** The number of items in @c userInfosArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger userInfosArray_Count;

@end

#pragma mark - RankInfo

typedef YF_ENUM(RankInfo_FieldNumber) {
  RankInfo_FieldNumber_UserId = 1,
  RankInfo_FieldNumber_ScoresArray = 2,
  RankInfo_FieldNumber_ExtendsInfo = 3,
};

/**
 * 用户在榜单中的信息
 **/
YF_FINAL @interface RankInfo : YFMessage

/** 用户ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 用户的成绩 */
@property(nonatomic, readwrite, strong, null_resettable) YFUInt32Array *scoresArray;
/** The number of items in @c scoresArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger scoresArray_Count;

/** 用户扩展信息，包括用户的name，icon等 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *extendsInfo;

@end

#pragma mark - UserRankReq

typedef YF_ENUM(UserRankReq_FieldNumber) {
  UserRankReq_FieldNumber_BundleId = 1,
  UserRankReq_FieldNumber_RankingIdArray = 2,
  UserRankReq_FieldNumber_UserId = 3,
  UserRankReq_FieldNumber_UserGeo = 4,
};

/**
 * 根据用户id获取对应榜单中的名次 /v1/r/rank
 **/
YF_FINAL @interface UserRankReq : YFMessage

/** 应用标识ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *bundleId;

/** 榜单ID */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *rankingIdArray;
/** The number of items in @c rankingIdArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger rankingIdArray_Count;

/** 用户uid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 用户geo */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userGeo;

@end

#pragma mark - UserRankResp

typedef YF_ENUM(UserRankResp_FieldNumber) {
  UserRankResp_FieldNumber_ListArray = 1,
};

/**
 * 获取用户对应榜单id名次响应(榜单不存在或者未上榜则不返回该榜单名次信息)
 **/
YF_FINAL @interface UserRankResp : YFMessage

/** 排榜信息，列表形式 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UserRankInfo*> *listArray;
/** The number of items in @c listArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger listArray_Count;

@end

#pragma mark - UserRankInfo

typedef YF_ENUM(UserRankInfo_FieldNumber) {
  UserRankInfo_FieldNumber_RankingId = 1,
  UserRankInfo_FieldNumber_Rank = 2,
  UserRankInfo_FieldNumber_ScoresArray = 3,
  UserRankInfo_FieldNumber_ExtendsInfo = 4,
};

YF_FINAL @interface UserRankInfo : YFMessage

/** 榜单id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *rankingId;

/** 所在名次 */
@property(nonatomic, readwrite) uint32_t rank;

/** 用户的成绩 */
@property(nonatomic, readwrite, strong, null_resettable) YFUInt32Array *scoresArray;
/** The number of items in @c scoresArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger scoresArray_Count;

/** 用户扩展信息，包括用户的name，icon等 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *extendsInfo;

@end

#pragma mark - FetchActivityReq

typedef YF_ENUM(FetchActivityReq_FieldNumber) {
  FetchActivityReq_FieldNumber_BundleId = 1,
  FetchActivityReq_FieldNumber_ActivityId = 2,
};

/**
 * 查看当前活动 /v2/a/fetch
 **/
YF_FINAL @interface FetchActivityReq : YFMessage

/** 应用标识ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *bundleId;

/** 活动ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *activityId;

@end

#pragma mark - FetchActivityResp

typedef YF_ENUM(FetchActivityResp_FieldNumber) {
  FetchActivityResp_FieldNumber_RoomNums = 1,
  FetchActivityResp_FieldNumber_RoomWeight = 2,
};

/**
 * 返回当前活动
 **/
YF_FINAL @interface FetchActivityResp : YFMessage

/** 房间人数 */
@property(nonatomic, readwrite) uint32_t roomNums;

/** 房间权重 */
@property(nonatomic, readwrite) uint32_t roomWeight;

@end

#pragma mark - JoinActivityReq

typedef YF_ENUM(JoinActivityReq_FieldNumber) {
  JoinActivityReq_FieldNumber_BundleId = 1,
  JoinActivityReq_FieldNumber_UserId = 2,
  JoinActivityReq_FieldNumber_ActivityId = 3,
  JoinActivityReq_FieldNumber_Weight = 4,
  JoinActivityReq_FieldNumber_EndTime = 5,
};

/**
 * 加入活动请求 /v1/a/join
 **/
YF_FINAL @interface JoinActivityReq : YFMessage

/** 应用标识ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *bundleId;

/** 用户ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 活动ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *activityId;

/** 权重 */
@property(nonatomic, readwrite) uint32_t weight;

/** 结束时间，用来清理房间 */
@property(nonatomic, readwrite) uint64_t endTime;

@end

#pragma mark - JoinActivityReqV2

typedef YF_ENUM(JoinActivityReqV2_FieldNumber) {
  JoinActivityReqV2_FieldNumber_BundleId = 1,
  JoinActivityReqV2_FieldNumber_UserId = 2,
  JoinActivityReqV2_FieldNumber_ActivityId = 3,
  JoinActivityReqV2_FieldNumber_Weight = 4,
  JoinActivityReqV2_FieldNumber_EndTime = 5,
  JoinActivityReqV2_FieldNumber_Active = 6,
  JoinActivityReqV2_FieldNumber_Tag = 7,
  JoinActivityReqV2_FieldNumber_ExtendsInfo = 8,
  JoinActivityReqV2_FieldNumber_Progress = 9,
  JoinActivityReqV2_FieldNumber_RoomId = 10,
  JoinActivityReqV2_FieldNumber_Score = 11,
};

/**
 * 加入活动 /v2/a/join
 **/
YF_FINAL @interface JoinActivityReqV2 : YFMessage

/** 应用标识ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *bundleId;

/** 用户ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 活动ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *activityId;

/** 权重 */
@property(nonatomic, readwrite) uint32_t weight;

/** 结束时间，用来清理房间 */
@property(nonatomic, readwrite) uint64_t endTime;

/** 活跃和非活跃 0.非活跃 1.活跃 */
@property(nonatomic, readwrite) uint32_t active;

/** 分组标签，相同标签的为一组 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *tag;

/** 用户扩展信息，包括用户的name，icon等 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *extendsInfo;

/** 活动进度，大于等于该值时，用户不能再加入该房间 */
@property(nonatomic, readwrite) uint32_t progress;

/** 活动房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;

/** 用于需要缓存前3的活动需要的分数 */
@property(nonatomic, readwrite) uint64_t score;

@end

#pragma mark - JoinActivityResp

typedef YF_ENUM(JoinActivityResp_FieldNumber) {
  JoinActivityResp_FieldNumber_RoomId = 1,
};

/**
 * 加入活动响应
 **/
YF_FINAL @interface JoinActivityResp : YFMessage

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;

@end

#pragma mark - ActivityScoreCommitReq

typedef YF_ENUM(ActivityScoreCommitReq_FieldNumber) {
  ActivityScoreCommitReq_FieldNumber_BundleId = 1,
  ActivityScoreCommitReq_FieldNumber_UserId = 2,
  ActivityScoreCommitReq_FieldNumber_ActivityId = 3,
  ActivityScoreCommitReq_FieldNumber_RoomId = 4,
  ActivityScoreCommitReq_FieldNumber_ExtendsInfo = 5,
  ActivityScoreCommitReq_FieldNumber_Progress = 6,
  ActivityScoreCommitReq_FieldNumber_Active = 7,
};

/**
 * 活动提交的数据 /v1/a/commit
 **/
YF_FINAL @interface ActivityScoreCommitReq : YFMessage

/** 应用标识ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *bundleId;

/** 用户ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 活动ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *activityId;

/** 活动房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;

/** 用户扩展信息，包括用户的name，icon等 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *extendsInfo;

/** 活动进度，大于等于该值时，用户不能再加入该房间 */
@property(nonatomic, readwrite) uint32_t progress;

/** 活跃和非活跃 0.非活跃 1.活跃 */
@property(nonatomic, readwrite) uint32_t active;

@end

#pragma mark - FetchActivityRoomReq

typedef YF_ENUM(FetchActivityRoomReq_FieldNumber) {
  FetchActivityRoomReq_FieldNumber_BundleId = 1,
  FetchActivityRoomReq_FieldNumber_ActivityId = 2,
  FetchActivityRoomReq_FieldNumber_RoomId = 3,
};

/**
 * 获取活动房间数据请求 /v2/a/fetchRoom
 **/
YF_FINAL @interface FetchActivityRoomReq : YFMessage

/** 应用标识ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *bundleId;

/** 活动ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *activityId;

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;

@end

#pragma mark - FetchActivityRoomResp

typedef YF_ENUM(FetchActivityRoomResp_FieldNumber) {
  FetchActivityRoomResp_FieldNumber_ActivityRoomInfoArray = 1,
};

/**
 * 获取活动房间数据响应
 **/
YF_FINAL @interface FetchActivityRoomResp : YFMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ActivityRoomInfo*> *activityRoomInfoArray;
/** The number of items in @c activityRoomInfoArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger activityRoomInfoArray_Count;

@end

#pragma mark - ActivityRoomInfo

typedef YF_ENUM(ActivityRoomInfo_FieldNumber) {
  ActivityRoomInfo_FieldNumber_UserId = 1,
  ActivityRoomInfo_FieldNumber_ExtendsInfo = 2,
};

/**
 * 活动房间数据
 **/
YF_FINAL @interface ActivityRoomInfo : YFMessage

/** 用户ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 用户扩展信息，包括用户的name，icon等 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *extendsInfo;

@end

#pragma mark - ActivityHistoryTopReq

typedef YF_ENUM(ActivityHistoryTopReq_FieldNumber) {
  ActivityHistoryTopReq_FieldNumber_BundleId = 1,
  ActivityHistoryTopReq_FieldNumber_ActivityId = 2,
};

/**
 * 获取活动历史前3玩家信息请求 /v2/a/fetchTopHistory
 **/
YF_FINAL @interface ActivityHistoryTopReq : YFMessage

/** 应用标识ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *bundleId;

/** 活动ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *activityId;

@end

#pragma mark - ActivityHistoryTopResp

typedef YF_ENUM(ActivityHistoryTopResp_FieldNumber) {
  ActivityHistoryTopResp_FieldNumber_ListArray = 1,
};

YF_FINAL @interface ActivityHistoryTopResp : YFMessage

/** 榜单列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<HistoryRankingInfo*> *listArray;
/** The number of items in @c listArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger listArray_Count;

@end

#pragma mark - HistoryRankingInfo

typedef YF_ENUM(HistoryRankingInfo_FieldNumber) {
  HistoryRankingInfo_FieldNumber_EndTime = 1,
  HistoryRankingInfo_FieldNumber_PlayerListArray = 2,
};

/**
 * 历史前3榜单信息
 **/
YF_FINAL @interface HistoryRankingInfo : YFMessage

/** 活动结算时间，该信息记录时间 */
@property(nonatomic, readwrite) uint64_t endTime;

/** 成员扩展信息列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *playerListArray;
/** The number of items in @c playerListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger playerListArray_Count;

@end

#pragma mark - RankingHistoryTopReq

typedef YF_ENUM(RankingHistoryTopReq_FieldNumber) {
  RankingHistoryTopReq_FieldNumber_BundleId = 1,
  RankingHistoryTopReq_FieldNumber_RankingId = 2,
  RankingHistoryTopReq_FieldNumber_Geo = 3,
  RankingHistoryTopReq_FieldNumber_EndTime = 4,
};

/**
 * 获取榜单历史前3玩家信息请求 /v1/r/fetchTopHistory
 **/
YF_FINAL @interface RankingHistoryTopReq : YFMessage

/** 应用标识ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *bundleId;

/** 排行榜ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *rankingId;

/** 地区排行榜需要传对应地区 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *geo;

/** 根据结算时间获取对应历史记录。由于服务器结算需要时间，会从这个时间再往后几秒范围获取 */
@property(nonatomic, readwrite) uint64_t endTime;

@end

#pragma mark - RankingHistoryTopResp

typedef YF_ENUM(RankingHistoryTopResp_FieldNumber) {
  RankingHistoryTopResp_FieldNumber_ListArray = 1,
};

YF_FINAL @interface RankingHistoryTopResp : YFMessage

/** 榜单列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<HistoryRankingInfoV2*> *listArray;
/** The number of items in @c listArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger listArray_Count;

@end

#pragma mark - HistoryRankingInfoV2

typedef YF_ENUM(HistoryRankingInfoV2_FieldNumber) {
  HistoryRankingInfoV2_FieldNumber_EndTime = 1,
  HistoryRankingInfoV2_FieldNumber_PlayerListArray = 2,
};

YF_FINAL @interface HistoryRankingInfoV2 : YFMessage

/** 榜单结算时间 */
@property(nonatomic, readwrite) uint64_t endTime;

/** 玩家信息列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<RankInfo*> *playerListArray;
/** The number of items in @c playerListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger playerListArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
